"""
RAG Implementation - Hands-on Exercise

This exercise demonstrates building a complete RAG pipeline.
"""

from typing import List, Dict, Any
import hashlib
import math


# ============================================================================
# Simple RAG Implementation
# ============================================================================


class SimpleRAGPipeline:
    """A simple RAG pipeline implementation."""

    def __init__(self, chunk_size: int = 500, overlap: int = 50):
        self.chunk_size = chunk_size
        self.overlap = overlap
        self.documents: List[Dict[str, Any]] = []
        self.chunks: List[Dict[str, Any]] = []

    def load_documents(self, docs: List[str], sources: List[str] = None):
        """Load and chunk documents."""
        sources = sources or [f"doc_{i}" for i in range(len(docs))]

        for i, doc in enumerate(docs):
            # Simple chunking
            chunks = self._chunk_text(doc)
            for j, chunk in enumerate(chunks):
                self.chunks.append(
                    {
                        "id": f"{sources[i]}_chunk_{j}",
                        "text": chunk,
                        "source": sources[i],
                        "index": j,
                    }
                )

    def _chunk_text(self, text: str) -> List[str]:
        """Simple text chunking."""
        words = text.split()
        chunks = []

        for i in range(0, len(words), self.chunk_size // 6):  # Approx 6 chars per word
            chunk = " ".join(words[i : i + self.chunk_size // 6])
            if chunk:
                chunks.append(chunk)

        return chunks if chunks else [text]

    def build_index(self):
        """Build an in-memory index (simplified)."""
        for chunk in self.chunks:
            # Create simple hash-based vectors
            chunk["vector"] = self._text_to_vector(chunk["text"])

    def _text_to_vector(self, text: str) -> List[float]:
        """Convert text to vector (simplified)."""
        import random

        hash_val = int(hashlib.md5(text.encode()).hexdigest()[:8], 16)
        random.seed(hash_val)
        return [random.uniform(-1, 1) for _ in range(384)]

    def retrieve(self, query: str, k: int = 3) -> List[Dict[str, Any]]:
        """Retrieve relevant chunks."""
        query_vector = self._text_to_vector(query)

        # Calculate similarities
        results = []
        for chunk in self.chunks:
            sim = sum(a * b for a, b in zip(query_vector, chunk["vector"]))
            results.append((chunk, sim))

        # Sort and return top k
        results.sort(key=lambda x: x[1], reverse=True)
        return [r[0] for r in results[:k]]

    def generate(self, query: str, retrieved_chunks: List[Dict]) -> str:
        """Generate response (simplified - in production use LLM)."""
        context = "\n\n".join([c["text"] for c in retrieved_chunks])

        return f"""
Based on the retrieved context, here's my answer to: "{query}"

[In production, this would be generated by an LLM]

Retrieved Context:
{context}

Sources: {[c["source"] for c in retrieved_chunks]}
"""

    def query(self, query: str, k: int = 3) -> Dict[str, Any]:
        """Full RAG query pipeline."""
        retrieved = self.retrieve(query, k)
        response = self.generate(query, retrieved)

        return {"query": query, "response": response, "sources": retrieved}


def main():
    """Demo the RAG pipeline."""

    print("=" * 60)
    print("RAG Implementation - Hands-on Exercise")
    print("=" * 60)

    # Sample documents
    documents = [
        "Python is a high-level programming language. It is known for readability and versatility.",
        "Machine learning is a subset of AI. It enables systems to learn from data.",
        "Deep learning uses neural networks with multiple layers to learn patterns.",
        "Natural language processing deals with understanding human language.",
        "RAG combines retrieval with generation for better AI responses.",
    ]

    # Create and populate pipeline
    rag = SimpleRAGPipeline(chunk_size=100, overlap=20)
    rag.load_documents(documents)
    rag.build_index()

    print(f"\nIndexed {len(rag.chunks)} chunks")

    # Query
    query = "What is machine learning?"
    result = rag.query(query)

    print(f"\nQuery: {query}")
    print(f"\nResponse: {result['response'][:200]}...")


if __name__ == "__main__":
    main()
