"""
RAG Implementation - Hands-on Exercise

This exercise demonstrates building a complete RAG pipeline.
"""

import sys
import os
from typing import List, Dict, Any

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "03_vector_databases"))
from exercise import HuggingFaceEmbedding, ChromaVectorStore


# ============================================================================
# Simple RAG Implementation
# ============================================================================


class SimpleRAGPipeline:
    """A simple RAG pipeline implementation."""

    def __init__(self, chunk_size: int = 500, overlap: int = 50):
        self.chunk_size = chunk_size
        self.overlap = overlap
        self.embed_fn = HuggingFaceEmbedding()
        self.vector_store = ChromaVectorStore()
        self.chunk_metadata: List[Dict[str, Any]] = []

    def load_documents(self, docs: List[str], sources: List[str] = None):
        """Load and chunk documents."""
        sources = sources or [f"doc_{i}" for i in range(len(docs))]
        
        for i, doc in enumerate(docs):
            for j, chunk in enumerate(self._chunk_text(doc)):
                self.chunk_metadata.append(
                    {"id": f"{sources[i]}_chunk_{j}", "text": chunk, "source": sources[i]}
                )

    def _chunk_text(self, text: str) -> List[str]:
        """Simple text chunking."""
        words = text.split()
        step = self.chunk_size // 6  # Approx 6 chars per word
        chunks = [" ".join(words[i : i + step]) for i in range(0, len(words), step)]
        return [c for c in chunks if c] or [text]

    def build_index(self):
        """Build an in-memory index."""
        for meta in self.chunk_metadata:
            self.vector_store.add(meta["id"], self.embed_fn.embed(meta["text"]), meta)

    def retrieve(self, query: str, k: int = 3) -> List[Dict[str, Any]]:
        """Retrieve relevant chunks."""
        query_vector = self.embed_fn.embed(query)
        results = self.vector_store.search(query_vector, k)
        return [meta for _, _, meta in results]

    def generate(self, query: str, retrieved_chunks: List[Dict]) -> str:
        """Generate response (simplified - in production use LLM)."""
        context = "\n\n".join([c["text"] for c in retrieved_chunks])

        return f"""
Based on the retrieved context, here's my answer to: "{query}"

[In production, this would be generated by an LLM]

Retrieved Context:
{context}

Sources: {[c["source"] for c in retrieved_chunks]}
"""

    def query(self, query: str, k: int = 3) -> Dict[str, Any]:
        """Full RAG query pipeline."""
        retrieved = self.retrieve(query, k)
        response = self.generate(query, retrieved)

        return {"query": query, "response": response, "sources": retrieved}


def main():
    """Demo the RAG pipeline."""

    print("=" * 60)
    print("RAG Implementation - Hands-on Exercise")
    print("=" * 60)

    # Sample documents
    documents = [
        "Python is a high-level programming language. It is known for readability and versatility.",
        "Machine learning is a subset of AI. It enables systems to learn from data.",
        "Deep learning uses neural networks with multiple layers to learn patterns.",
        "Natural language processing deals with understanding human language.",
        "RAG combines retrieval with generation for better AI responses.",
    ]

    # Create and populate pipeline
    rag = SimpleRAGPipeline(chunk_size=100, overlap=20)
    rag.load_documents(documents)
    rag.build_index()

    print(f"\nIndexed {len(rag.chunk_metadata)} chunks")

    # Query
    query = "What is machine learning?"
    result = rag.query(query)

    print(f"\nQuery: {query}")
    print(f"\nResponse: {result['response'][:200]}...")


if __name__ == "__main__":
    main()
